def TF = "ECR"

pipeline {
    agent {
        label 'worker_node1'
    }
    tools {
        terraform 'tf_test' //set up this name in jenkins
        }

    stages {
        stage('Checkout') {
            steps {
                // Get some code from a GitHub repository
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Research-Associate-Internship/Hyunmin-Choi.git']]])
        
            }
        }  

        
        stage('terraform') {
            steps {
                dir("${WORKSPACE}/Terraform/${TF}") {
                sh 'ls'
                sh 'pwd'
                sh 'terraform init'
                }
            }
        }
        
        stage("plan") {
          steps {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws_credentials', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                    dir("${WORKSPACE}/Terraform/${TF}") {
                    sh 'terraform plan'
                    }
            }
          }
        }
        
        stage("apply") {
          steps {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws_credentials', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                    dir("${WORKSPACE}/Terraform/${TF}") {
                    sh 'terraform apply --auto-approve'
                    }
            }
          }
        }
      
        stage("destroy") {
          input {
            message "Ready to destroy?"
            ok "Yes"
          }
          
          steps {
            withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', accessKeyVariable: 'AWS_ACCESS_KEY_ID', credentialsId: 'aws_credentials', secretKeyVariable: 'AWS_SECRET_ACCESS_KEY']]) {
                    dir("${WORKSPACE}/Terraform/${TF}") {
                    sh 'terraform destroy --auto-approve'
                    }
            }
          }
        }
      
    }
}
          
